version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  app:
    build: ./
    ports:
      - "8080:8080"
    links:
      - mongodb
    environment:
      MICRONAUT_SERVER_HOST: app
      MONGO_HOST: mongodb
      MONGO_PORT: 27017