micronaut:
  application:
    name: storeMicronautKotlin
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
mongodb:
  uri: mongodb://${MONGO_HOST:""}:${MONGO_PORT:""}/store
jackson:
  serializationInclusion: ALWAYS
  dateFormat: yyyy-MM-dd'T'HH:mm:ss
  timeZone: America/Sao_Paulo